def f() -> int:
    error_here()
    return 1

f(wat=1)
